#!/usr/bin/bash

export JAVA_8_HOME=$(/usr/libexec/java_home -v 1.8)
export JAVA_LATEST_HOME=$(/usr/libexec/java_home)
export JAVA_HOME=$JAVA_8_HOME
export HTTP_PROXY="http://127.0.0.1:8118"
export HTTPS_PROXY="https://127.0.0.1:8118"
export NO_PROXY="localhost,127.0.0.1,localaddress,.localdomain.com"

alias ls='exa'
alias la="exa -lha"

export PATH="$HOME/.jenv/bin:$PATH"
#eval "$(jenv init -)"
